<a href="https://colab.research.google.com/github/pratik20034/Pratheek/blob/main-point/Welcome_To_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

import the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
tf.__version__

'2.9.2'

In [4]:
dataset=pd.read_csv('Churn_Modelling.csv')
x=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values
print(x)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


encoding categorical data
label encoding the"gender" column 

In [5]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


onehot encoding the "geography" column

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x=np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


splitting the dataset into training set and test set

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)


feature scaling

In [14]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

part 2- building the ann

initializing the ANN

In [19]:
ann=tf.keras.models.Sequential()

adding the input layer and the first hidden layer

In [21]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

adding the second hidden layer

In [23]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

part 3 training the ANN

compiling the ANN

In [24]:
from tensorflow.python import metrics
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [27]:
ann.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5833 - accuracy: 0.7169
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4967 - accuracy: 0.7930
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4669 - accuracy: 0.7965
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4484 - accuracy: 0.8000
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4342 - accuracy: 0.8130
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4245 - accuracy: 0.8167
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4172 - accuracy: 0.8177
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4112 - accuracy: 0.8207
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4059 - accuracy: 0.8230
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4011 - accura

predicting rhe result of a single observation

In [25]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

1/1 [==============================] - 0s 425ms/step
[[False]]


predicting the test set results

In [28]:
y_pred=ann.predict(x_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


making the confusion matrix

In [29]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1510   85]
 [ 193  212]]


0.861